export const site = {
  name: "Ranit Naskar",
  brand: "ECLIPSE",
  role: "Software Developer",
  tagline: "Full-stack development at the edge of light.",
  email: "ranitnaskar09032007@gmail.com",
  phone: "+91 9002036816",
  github: "https://github.com/R4NiTeXe",
  linkedin: "https://www.linkedin.com/in/ranit-naskar/",
  portfolio: "your-portfolio.com",
  availability: "Available for work",
  location: "Kolkata, West Bengal, India",
  education: "Diploma in CSE — Brainware University (Expected 2027)",
  languages: ["English", "Bengali", "Hindi"],
} as const;

export const navLinks = [
  { label: "About", href: "#about" },
  { label: "Skills", href: "#skills" },
  { label: "Work", href: "#work" },
  { label: "Journey", href: "#journey" },
  { label: "Contact", href: "#contact" },
] as const;

export const techStack = [
  "C",
  "C++",
  "HTML",
  "CSS",
  "JavaScript",
  "React.js",
  "Tailwind CSS",
  "Node.js",
  "Express.js",
  "REST APIs",
  "MongoDB",
  "MySQL",
  "Git",
  "GitHub",
  "Linux",
  "Docker",
  "Vercel",
  "Render",
  "GSAP",
  "Three.js",
  "Postman",
  "DSA",
  "DBMS",
  "OOP",
] as const;
