export const site = {
  name: "Ranit Naskar",
  brand: "Ranit Naskar",
  role: "Software Developer",
  tagline: "Building full-stack systems from idea to deployment.",
  email: "ranitnaskar09032007@gmail.com",
  phone: "+91 9002036816",
  github: "https://github.com/R4NiTeXe",
  linkedin: "https://www.linkedin.com/in/ranit-naskar/",
  availability: "Available for work",
  location: "Kolkata, West Bengal, India",
  url: "https://ranitnaska.me",
} as const;

export const navLinks = [
  { label: "About", href: "#about" },
  { label: "Skills", href: "#skills" },
  { label: "Work", href: "#work" },
  { label: "Experience", href: "#experience" },
  { label: "Journey", href: "#journey" },
  { label: "Games", href: "#games" },
  { label: "Contact", href: "#contact" },
] as const;

export const techStack = [
  "C",
  "C++",
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React.js",
  "Next.js",
  "Tailwind CSS",
  "shadcn/ui",
  "Node.js",
  "Express.js",
  "REST APIs",
  "JWT",
  "RBAC",
  "Zod",
  "Mongoose",
  "MongoDB",
  "MySQL",
  "Redis",
  "TanStack Query",
  "Redux Toolkit",
  "GSAP",
  "Motion",
  "Three.js",
  "React Three Fiber",
  "Vitest",
  "Supertest",
  "Cypress",
  "Swagger/OpenAPI",
  "Postman",
  "Git",
  "GitHub",
  "Linux",
  "Docker",
  "Docker Compose",
  "Nginx",
  "Vercel",
  "Render",
  "DSA",
  "DBMS",
  "OOP",
] as const;
